redis:
  addr: 127.0.0.1:6379
  passwd: 123@123

kafka:
  addr: 1

postgresql:
  writeDSN: "postgres://lql:lql@123@192.168.31.164:30432/lqldb?sslmode=disable"
  readDSN: "postgres://lql:lql@123@192.168.31.164:30433/lqldb?sslmode=disable"
